# -*- coding: utf-8 -*-
"""FinalRandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OP2uqkAjxDPQaWhHTAxG-rbAmqdV2cxl
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from skimage.feature import graycomatrix, graycoprops

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

data_dir = "/content/drive/MyDrive/Dataset_Daun_Mangga"
img_size = (256, 256)

def extract_glcm_features(img):
  gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  gray = cv2.resize(gray, img_size)

  glcm = graycomatrix(
      gray,
      distances=[1],
      angles=[0, np.pi/4, np.pi/2, 3*np.pi/4],
      levels=256,
      symmetric=True,
      normed=True
  )

  contrast = graycoprops(glcm, 'contrast').mean()
  correlation = graycoprops(glcm, 'correlation').mean()
  energy = graycoprops(glcm, 'energy').mean()
  homogeneity = graycoprops(glcm, 'homogeneity').mean()

  return [contrast, correlation, energy, homogeneity]

X = []
y = []

for label in os.listdir(data_dir):
  label_dir = os.path.join(data_dir, label)
  if not os.path.isdir(label_dir):
    continue

  for file in os.listdir(label_dir):
    file_path = os.path.join(label_dir, file)
    img = cv2.imread(file_path)

    if img is not None:
      features = extract_glcm_features(img)
      X.append(features)
      y.append(label)

X = np.array(X)
y = np.array(y)

print("Jumlah data:", len(X))
# print("Contoh fitur GLCM:", X[0])

le = LabelEncoder()
y = le.fit_transform(y)

class_names = le.classes_
print("Nama kelas:", class_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(
    n_estimators=100, random_state=42
)

rf_model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

print("\nConfusion Matrix:")
print(classification_report(y_test, y_pred, target_names=class_names))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 6))
plt.imshow(cm, cmap="Blues")
plt.xticks(range(len(class_names)), class_names, rotation=45)
plt.yticks(range(len(class_names)), class_names)
plt.title("Confusion Matrix")
plt.colorbar()
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

def predict_image_rf(img_path, model, le):
    img = cv2.imread(img_path)
    if img is None:
        print("Gambar tidak ditemukan!")
        return None

    features = extract_glcm_features(img)
    features = np.array(features).reshape(1, -1)

    pred = model.predict(features)
    label = le.inverse_transform(pred)[0]

    proba = model.predict_proba(features)
    confidence = np.max(proba) * 100

    return label, confidence

test_image_path = "/content/drive/MyDrive/Dataset_Daun_Mangga/DSCF0244.JPG"

result, confidence = predict_image_rf(test_image_path, rf_model, le)

print("Hasil Prediksi:", result)
print("Tingkat Keyakinan: {:.2f}%".format(confidence))

import pickle

with open('rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

print("Model saved!")

from google.colab import files
files.download('rf_model.pkl')
files.download('label_encoder.pkl')

!pip install flask flask-cors pyngrok scikit-image opencv-python-headless -q

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import pickle
# import numpy as np
# import cv2
# from flask import Flask, request, jsonify
# from flask_cors import CORS
# from skimage.feature import graycomatrix, graycoprops
# 
# app = Flask(__name__)
# CORS(app)
# 
# with open('rf_model.pkl', 'rb') as f:
#     model = pickle.load(f)
# 
# with open('label_encoder.pkl', 'rb') as f:
#     le = pickle.load(f)
# 
# IMG_SIZE = (256, 256)
# 
# def extract_glcm_features(img):
#     """Same GLCM logic as your training script."""
#     gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#     gray = cv2.resize(gray, IMG_SIZE)
# 
#     glcm = graycomatrix(
#         gray,
#         distances=[1],
#         angles=[0, np.pi/4, np.pi/2, 3*np.pi/4],
#         levels=256,
#         symmetric=True,
#         normed=True
#     )
# 
#     contrast    = graycoprops(glcm, 'contrast').mean()
#     correlation = graycoprops(glcm, 'correlation').mean()
#     energy      = graycoprops(glcm, 'energy').mean()
#     homogeneity = graycoprops(glcm, 'homogeneity').mean()
# 
#     return [contrast, correlation, energy, homogeneity]
# 
# @app.route('/predict', methods=['POST'])
# def predict():
#     if 'image' not in request.files:
#         return jsonify({
#             'is_success': False,
#             'error_message': 'No image provided',
#             'category': '',
#             'confidence': 0.0
#         }), 400
# 
#     file = request.files['image']
#     file_bytes = np.frombuffer(file.read(), np.uint8)
#     img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
# 
#     if img is None:
#         return jsonify({
#             'is_success': False,
#             'error_message': 'Invalid image format',
#             'category': '',
#             'confidence': 0.0
#         }), 400
# 
#     try:
#         features = extract_glcm_features(img)
#         features_arr = np.array(features).reshape(1, -1)
# 
#         pred       = model.predict(features_arr)
#         proba      = model.predict_proba(features_arr)
#         confidence = float(np.max(proba))
#         category   = le.inverse_transform(pred)[0]
# 
#         return jsonify({
#             'is_success':    True,
#             'category':      category,
#             'confidence':    confidence,
#             'error_message': None
#         })
# 
#     except Exception as e:
#         return jsonify({
#             'is_success':    False,
#             'error_message': str(e),
#             'category':      '',
#             'confidence':    0.0
#         }), 500
# 
# @app.route('/health', methods=['GET'])
# def health():
#     return jsonify({'status': 'ok', 'classes': list(le.classes_)})
# 
# if __name__ == '__main__':
#     app.run(debug=False)

from pyngrok import ngrok
import threading

ngrok.set_auth_token("3AM10qmn8hnNF8vKmmw3aTAf6Qu_3558vKsMAWzm7DM1crJL1")

def run_flask():
    import subprocess
    subprocess.run(["python", "app.py"])

thread = threading.Thread(target=run_flask)
thread.daemon = True
thread.start()

import time
time.sleep(3)

public_url = ngrok.connect(5000)
print("=" * 50)
print(f"🚀 API URL: {public_url}/predict")
print("=" * 50)
print("Copy this URL into your Flutter app!")