import 'library_item_data.dart';

final List<LibraryItemData> libraryItemsMock = [
  const LibraryItemData(
    title: 'Anthracnose',
    subtitle: 'JAMUR • COLLETOTRICHUM',
    shortDescription: 'Bercak hitam cekung pada buah...',
    originalName: '(Penyakit Antraknosa)',
    status: 'Penyakit Utama',
    type: 'Fungal Pathogen',
    description: 'Anthracnose merupakan salah satu penyakit paling merugikan pada tanaman mangga. Penyakit ini disebabkan oleh jamur Colletotrichum gloeosporioides yang menyerang daun, bunga, dan buah mangga, menyebabkan bercak hitam yang dapat menurunkan hasil panen secara drastis. Biasanya ukuran panjang spora : ± 17 µm dan lebar spora: ±3,5 µm',
    partsAttacked: {
      'Daun': 'Bercak coklat kehitaman dengan tepi kuning.',
      'Buah': 'Bercak hitam cekung yang meluas saat penyimpanan.',
      'Bunga': 'Menyebabkan gugur bunga massal.',
    },
    earlyPhase: 'Muncul bercak kecil berwarna coklat kemerahan pada daun muda. Pada kondisi lembap, bercak meluas dengan cepat dan berwarna hitam.',
    chronicPhase: 'Bercak hitam meluas menutupi sebagian besar daun. Daun mengering dan gugur. Buah menunjukkan busuk hitam yang dapat meluas hingga ke daging buah.',
    technicalControl: [
      'Pangkas dan musnahkan bagian tanaman yang terinfeksi.',
      'Jaga kebersihan kebun dari sisa-sisa tanaman sakit.',
      'Setelah panen, buah dapat direndam dalam air hangat 55°C selama 5 menit untuk mencegah infeksi lanjutan.',
    ],
    chemicalControlInfo: '"Fungisida seperti bubur Bordeaux atau berbahan aktif benomyl, mancozeb atau tembaga oksiklorida sangat efektif jika diaplikasikan secara preventif."',
    chemicalDose: '2g/L air setiap 7-10 hari',
    chemicalTime: 'Awal musim hujan atau kelembapan tinggi',
    spreadWarning: 'Spora jamur menyebar melalui percikan air hujan dan angin. Hindari penyiraman di atas daun untuk memperlambat penyebaran.',
  ),
  const LibraryItemData(
    title: 'Daun Sehat',
    subtitle: 'STATUS NORMAL',
    shortDescription: 'Tidak ditemukan patogen atau...',
    originalName: '(Status Normal)',
    status: 'Normal',
    type: 'Healthy',
    description: 'Tanaman dalam kondisi prima dan tidak menunjukkan gejala serangan penyakit atau hama. Daun sehat adalah kunci utama untuk proses fotosintesis yang optimal dan produksi buah yang maksimal.',
    partsAttacked: {
      'Daun': 'Hijau segar, permukaan rata, tulang daun terlihat jelas.',
      'Ranting': 'Kuat dan tidak menunjukkan tanda-tanda pengeringan atau luka.',
      'Buah': 'Perkembangan normal tanpa bercak atau kelainan bentuk.',
    },
    earlyPhase: 'Tunas baru tumbuh normal dan vigor.',
    chronicPhase: 'Daun dewasa berwarna hijau tua mengkilap dan berfungsi optimal.',
    technicalControl: [
      'Lakukan pemupukan berimbang sesuai fase pertumbuhan tanaman.',
      'Rutin bersihkan gulma di sekitar piringan tanaman.',
      'Pemangkasan pemeliharaan untuk mengatur tajuk dan sirkulasi udara.',
    ],
    chemicalControlInfo: '"Penggunaan pupuk daun atau biostimulan dapat diberikan untuk mempertahankan kondisi optimal tanaman."',
    chemicalDose: 'Sesuai anjuran pada kemasan produk',
    chemicalTime: 'Pagi hari atau sesuai jadwal pemupukan rutin',
    spreadWarning: 'Kondisi tanaman sehat harus dijaga dengan memonitor kebun secara berkala untuk mendeteksi dini masuknya hama atau penyakit.',
  ),
  const LibraryItemData(
    title: 'Die Back',
    subtitle: 'JAMUR • LASIODIPLODIA',
    shortDescription: 'Ranting mengering dari ujung ke...',
    originalName: '(Penyakit Mati Ranting)',
    status: 'Penyakit Utama',
    type: 'Fungal Pathogen',
    description: 'Die Back adalah penyakit serius yang menyebabkan kematian jaringan tanaman dari ujung ranting ke arah pangkal. Disebabkan oleh jamur Lasiodiplodia theobromae yang sering menyerang tanaman yang mengalami stres akibat kekeringan atau luka.',
    partsAttacked: {
      'Ranting': 'Mengering dari ujung ke pangkal secara progresif.',
      'Batang': 'Munculnya kanker (canker) berwarna coklat gelap.',
      'Daun': 'Layu dan mengering mengikuti kematian ranting.',
    },
    earlyPhase: 'Ujung ranting mulai mengering dan daun layu tanpa sebab yang jelas. Kulit ranting berubah warna menjadi coklat.',
    chronicPhase: 'Pengeringan merambat ke cabang yang lebih besar. Muncul getah berwarna gelap pada batang. Jika tidak ditangani, dapat mematikan seluruh pohon.',
    technicalControl: [
      'Segera pangkas bagian yang terinfeksi hingga 15cm di bawah jaringan sehat.',
      'Sterilkan alat pemangkas dengan alkohol 70% setiap kali digunakan.',
    ],
    chemicalControlInfo: '"Aplikasi pasta fungisida berbahan tembaga pada luka pangkasan sangat krusial untuk mencegah infeksi lanjutan."',
    chemicalDose: 'Oleskan merata pada seluruh permukaan luka',
    chemicalTime: 'Segera setelah pemangkasan dilakukan',
    spreadWarning: 'Die Back sangat mudah menyebar pada tanaman yang mengalami stres. Pastikan drainase lahan baik dan hindari perlukaan tidak perlu pada batang.',
  ),
  const LibraryItemData(
    title: 'Gall Midge',
    subtitle: 'HAMA • SERANGGA',
    shortDescription: 'Benjolan kecil pada permukaan...',
    originalName: '(Serangan Lalat Puru)',
    status: 'Hama Utama',
    type: 'Insect Pest',
    description: 'Gall Midge adalah lalat kecil yang larvanya menyerang daun muda mangga dan membentuk puru (gall atau lebih dikenal dengan sebutan bintil daun) sebagai tempat tinggal dan sumber makanan. Serangan berat dapat menyebabkan daun muda gagal berkembang dan menghambat fotosintesis.',
    partsAttacked: {
      'Daun Muda': 'Pembentukan puru (bengkak) berbentuk bulat.',
      'Flush Baru': 'Daun muda menggulung dan tidak bisa membuka.',
      'Tangkai Daun': 'Deformasi dan pemendekan tangkai.',
    },
    earlyPhase: 'Muncul benjolan kecil berwarna hijau pada permukaan daun muda. Bintil berwarna keperakan.',
    chronicPhase: 'Puru membesar dan berubah warna menjadi coklat. Larva berkembang di dalam puru sebelum menjadi imago. Daun mengering dan gugur prematur.',
    technicalControl: [
      'Pangkas dan musnahkan daun yang sudah menunjukkan gejala awal, lakukan secara rutin untuk mencegah penyebaran dari siklus ulang hama.',
      'Sinkronkan waktu pemupukan agar flush daun tidak bersamaan dengan puncak aktivitas serangga.',
    ],
    chemicalControlInfo: '"Insektisida sistemik berbahan imidakloprid paling efektif diaplikasikan saat flush daun baru mulai muncul."',
    chemicalDose: '1-2 ml/L air setiap 7 hari',
    chemicalTime: 'Saat muncul flush daun muda baru',
    spreadWarning: 'Serangga dewasa aktif pada pagi dan sore hari. Pemasangan perangkap kuning (yellow sticky trap) dapat membantu memantau populasi.',
  ),
  const LibraryItemData(
    title: 'Powdery Mildew',
    subtitle: 'JAMUR • OIDIUM MANGIFERAE',
    shortDescription: 'Lapisan putih seperti bedak pada...',
    originalName: '(Penyakit Embun Tepung)',
    status: 'Penyakit Utama',
    type: 'Fungal Pathogen',
    description: 'Powdery Mildew merupakan salah satu tantangan agronomis paling signifikan bagi tanaman mangga. Penyakit ini dicirikan oleh pertumbuhan miselium putih yang menyerupai tepung pada organ vital tanaman, yang jika tidak dikendalikan dapat menyebabkan kegagalan panen total.',
    partsAttacked: {
      'Daun': 'Fokus pada permukaan atas dan bawah.',
      'Ranting Muda': 'Jaringan lunak yang sedang tumbuh.',
      'Tangkai Bunga': 'Area paling kritis saat musim berbunga.',
    },
    earlyPhase: 'Permukaan daun atau ranting muda tertutupi oleh lapisan tepung berwarna putih. Pada serangan lebih lanjut daun melengkung atau bergelombang.',
    chronicPhase: 'Serangan berat pada ranting muda dapat menyebabkan kematian jaringan (necrosis), sedangkan pada tangkai bunga menyebabkan kerontokan bunga dan buah muda secara masif.',
    technicalControl: [
      'Memotong daun atau tunas yang sudah terinfeksi.',
      'Sisa potongan wajib dibakar atau dibenamkan di tanah sedalam 15-40 cm untuk mencegah spora kembali menyebar.',
    ],
    chemicalControlInfo: '"Penyemprotan serbuk belerang murni sangat efektif jika diaplikasikan pada waktu yang tepat."',
    chemicalDose: '± 40 kg per Hektar (ha)',
    chemicalTime: 'Pagi hari saat bunga & daun berselimut embun',
    spreadWarning: 'Konidia pathogen ini adalah airborne. Spora sangat ringan dan mudah tersebar dalam jarak yang sangat jauh dengan bantuan angin, memungkinkan infeksi antar kebun terjadi dalam waktu singkat.',
  ),
  const LibraryItemData(
    title: 'Sooty Mould',
    subtitle: 'JAMUR • MELIOLA MANGIFERAE',
    shortDescription: 'Lapisan hitam seperti jelaga di...',
    originalName: '(Penyakit Kapang Jelaga/Embun Jelaga)',
    status: 'Penyakit Sekunder',
    type: 'Fungal Pathogen',
    description: 'Sooty Mould adalah lapisan jamur berwarna hitam seperti jelaga yang tumbuh di atas embun madu yang dihasilkan oleh serangga seperti kutu daun dan kutu putih. Penyakit ini secara tidak langsung menghambat fotosintesis dengan menutupi permukaan daun.',
    partsAttacked: {
      'Daun': 'Lapisan hitam menutupi permukaan atas.',
      'Ranting': 'Jelaga menempel pada kulit ranting.',
      'Buah': 'Menurunkan nilai estetika dan kualitas buah.',
    },
    earlyPhase: 'Muncul bercak hitam seperti jelaga pada permukaan daun bagian atas. Lapisan dapat dihapus dengan jari dan meninggalkan permukaan daun normal.',
    chronicPhase: 'Lapisan jelaga menutupi seluruh permukaan daun sehingga menghambat fotosintesis. Tanaman terlihat kerdil dan produksi buah menurun.',
    technicalControl: [
      'Kendalikan populasi serangga penghasil embun madu terlebih dahulu (ordo Hemiptera).',
      'Pangkas bagian tanaman yang reinfeksi.',
      'Musnahkan dengan cara dibakar atau dipendam (15-40 cm).',
    ],
    chemicalControlInfo: '"Pengendalian serangga vektor (kutu daun/kutu putih) adalah kunci utama. Gunakan fungisida berbahan aktif morestan atau alternatifnya dapat menyemprotkan tepung belerang."',
    chemicalDose: '±1,5 g/l air larutan fungisida disemprotkan ke bagian yang terinfeksi',
    chemicalTime: 'Saat populasi serangga mulai terdeteksi',
    spreadWarning: 'Sooty Mould adalah indikator adanya serangan serangga. Tangani dulu sumber masalahnya (serangga) sebelum membersihkan jelaga.',
  ),
];
